name: Flutter Nightly Build

on:
  schedule:
    # schedule build every night
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  # check_date:
  #   runs-on: ubuntu-latest
  #   name: Check latest commit
  #   outputs:
  #     should_run: ${{ steps.should_run.outputs.should_run }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: print latest_commit
  #       run: echo ${{ github.sha }}

  #     - id: should_run
  #       continue-on-error: true
  #       name: check latest commit is less than a day
  #       if: ${{ github.event_name == 'schedule' }}
  #       run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"

  check_date:
    name: Get release body
    id: get_release_body
    uses: actions/github-script@v7
    with:
      script: |
        const response = await github.request('GET /repos/{owner}/{repo}/releases/tags/{tag}', {
          owner: context.repo.owner,
          repo: context.repo.repo,
          tag: 'nightly',
        });
        // 终止流水线
        // if (response.data.body == '${{ github.sha }}') {
        //   core.setFailed('The current version has been built');
        // }
        return response.data.body == '${{ github.sha }}';

  run-flutter-nightly-build:
    needs: check_date
    if: ${{ steps.get_release_body.outputs.result != 'true' }}
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
